# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
python:
  - 2.7
  - 3.4
install:
    pip install Composite-Plate.git
script:
    python ./composite_plate/classical_plate_theory_test.py
