# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
python:
  - "2.7"
  - "3.4"
# command to install dependencies
install:
    pip install git+https://github.com/johnrbnsn/Composite-Plate.git
# command to run tests
script:
    python ./composite_plate/classical_plate_theory_test.py
